from src.gui.windows.models.explainers.decisiontree import DecisionTreeExplainerDialog
from src.gui.windows.models.explainers.discriminant import DiscriminantExplainerDialog
from src.gui.windows.models.explainers.extremeboosting import ExtremeBoostingTreeExplainerDialog
from src.gui.windows.models.explainers.knn import KNNExplainerDialog
from src.gui.windows.models.explainers.logistic import LogisticExplainerDialog
from src.gui.windows.models.explainers.naivebayes import NaiveBayesExplainerDialog
from src.gui.windows.models.explainers.nn import NeuralNetworkExplainerDialog
from src.gui.windows.models.explainers.randomforest import RandomForestExplainerDialog
from src.gui.windows.models.explainers.svm import SVMExplainerDialog
