from gui.dialogs.models.train.decisiontree import DecisionTreeTrainDialog
from gui.dialogs.models.train.randomforest import RandomForestTrainDialog
from gui.dialogs.models.train.knearestneighbors import KNearestNeighborsTrainDialog
from gui.dialogs.models.train.naivebayes import NaiveBayesTrainDialog
from gui.dialogs.models.train.logistic import LogisticRegressionTrainDialog
from gui.dialogs.models.train.svm import SupportVectorMachineTrainDialog
from gui.dialogs.models.train.extremeboosting import ExtremeBoostingTrainDialog
from gui.dialogs.models.train.neuralnetwork import NeuralNetworkTrainDialog
from gui.dialogs.models.train.voting import VotingModelDialog
